version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./assets:/app/assets
      - ./outputs:/app/outputs
      # Use bind mount for config files
      - type: bind
        source: ./.env
        target: /app/.env
      - type: bind
        source: ./gcloud-key.json
        target: /app/gcloud-key.json
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 